"""Fail-closed validation for the frozen LedgerGuard Part 1 foundation."""

from __future__ import annotations

import json
from collections.abc import Mapping
from hashlib import sha256
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator
from jsonschema.exceptions import SchemaError

PROJECT = "ledgerguard-payment-reconciliation-platform"
EXPECTED_TARGET = {
    "repository": "bhuvaneshwaranmurugan21/ledgerguard-payment-reconciliation-platform",
    "default_branch": "main",
    "account_id": "857229544428",
    "region": "ap-southeast-2",
    "oidc_role_name": "LedgerGuardGitHubOidcRole",
}
EXPECTED_RUNTIME = {
    "glue_version": "5.1",
    "python_version": "3.11",
    "spark_version": "3.5.6",
}
EVIDENCE_LEVELS = ["DESIGNED/MODELED", "LOCAL_VERIFIED", "AWS_VERIFIED", "UNCLAIMED"]
SCHEMA_NAMES = {
    "bank-entry-v1.schema.json",
    "case-revision-v1.schema.json",
    "journal-v1.schema.json",
    "processor-event-v1.schema.json",
    "processor-settlement-v1.schema.json",
    "reconciliation-policy-v1.schema.json",
    "reconciliation-proof-v1.schema.json",
    "run-manifest-v1.schema.json",
}
REQUIRED_DOCS = {
    "README.md",
    "PROJECT_STATUS.md",
    "docs/architecture.md",
    "docs/correctness.md",
    "docs/failure-model.md",
    "docs/gap-audit.md",
    "docs/scorecard.md",
    "docs/adr/0001-two-grain-reconciliation.md",
    "docs/adr/0002-parquet-proof-storage.md",
    "docs/adr/0003-late-data-revisions.md",
}
FORBIDDEN_PATHS = {"docs/INTERVIEW.md"}
FORBIDDEN_TEXT = (
    "".join(("co", "dex")),
    "".join(("ai", "-assisted")),
    "".join(("generated by ", "ai")),
    "".join(("aws", "_lab_verified")),
)
FORBIDDEN_REGION = "-".join(("ap", "south", "1"))


class FoundationError(ValueError):
    """Raised when the checked-in foundation violates its frozen contract."""


def _load_json(path: Path) -> dict[str, Any]:
    try:
        value: object = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise FoundationError(f"cannot load JSON {path}: {error}") from error
    if not isinstance(value, dict):
        raise FoundationError(f"JSON object required: {path}")
    return value


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise FoundationError(message)


def _validate_schemas(root: Path) -> dict[str, str]:
    contract_dir = root / "contracts"
    actual = {path.name for path in contract_dir.glob("*.schema.json")}
    _require(actual == SCHEMA_NAMES, f"schema inventory differs: {sorted(actual ^ SCHEMA_NAMES)}")
    digests: dict[str, str] = {}
    identifiers: set[str] = set()
    for name in sorted(SCHEMA_NAMES):
        path = contract_dir / name
        schema = _load_json(path)
        try:
            Draft202012Validator.check_schema(schema)
        except SchemaError as error:
            raise FoundationError(f"invalid schema {name}: {error.message}") from error
        identifier = schema.get("$id")
        if not isinstance(identifier, str) or not identifier:
            raise FoundationError(f"schema $id missing: {name}")
        _require(identifier not in identifiers, f"duplicate schema $id: {identifier}")
        identifiers.add(identifier)
        digests[name] = sha256(path.read_bytes()).hexdigest()
    return digests


def _validate_target(root: Path) -> dict[str, Any]:
    target = _load_json(root / ".github/ledgerguard-target.json")
    for key, expected in EXPECTED_TARGET.items():
        _require(target.get(key) == expected, f"target {key} must equal {expected}")
    _require(target.get("managed_runtime") == EXPECTED_RUNTIME, "managed runtime differs")
    return target


def _validate_completion(root: Path, target: Mapping[str, Any]) -> dict[str, Any]:
    completion = _load_json(root / "contracts/project-completion-v1.json")
    _require(completion.get("project") == PROJECT, "completion project differs")
    _require(completion.get("state") == "PART1_FOUNDATION_FROZEN", "foundation state differs")
    _require(completion.get("evidence_levels") == EVIDENCE_LEVELS, "evidence vocabulary differs")

    parts = completion.get("parts")
    if not isinstance(parts, list):
        raise FoundationError("completion parts must be a list")
    part_mappings: list[Mapping[str, Any]] = []
    for part in parts:
        if not isinstance(part, Mapping):
            raise FoundationError("every completion part must be an object")
        part_mappings.append(part)
    part_numbers = [part.get("part") for part in part_mappings]
    _require(part_numbers == [1, 2, 3, 4, 5], "completion parts must be exactly 1 through 5")
    _require(
        all(isinstance(part.get("gates"), list) and part["gates"] for part in part_mappings),
        "part gates missing",
    )
    workload_parts = [
        part.get("part") for part in part_mappings if part.get("aws_workload_allowed") is True
    ]
    _require(workload_parts == [4], "managed workload must be allowed only in Part 4")

    scorecard = completion.get("scorecard")
    if not isinstance(scorecard, Mapping) or len(scorecard) != 12:
        raise FoundationError("scorecard must have 12 dimensions")
    for dimension, value in scorecard.items():
        _require(
            isinstance(value, (int, float)) and not isinstance(value, bool) and 7 < value <= 10,
            f"scorecard target {dimension} must be above 7 and at most 10",
        )

    aws_boundary = completion.get("aws_boundary")
    if not isinstance(aws_boundary, Mapping):
        raise FoundationError("completion AWS boundary missing")
    for key in ("account_id", "region", "oidc_role_name"):
        _require(
            aws_boundary.get(key) == target.get(key), f"completion and target differ for {key}"
        )
    _require(aws_boundary.get("gross_project_cost_ceiling_usd") == 10, "cost ceiling differs")
    _require(
        aws_boundary.get("managed_runtime") == "AWS Glue 5.1 / Spark 3.5.6 / Python 3.11",
        "completion runtime differs",
    )
    return completion


def _validate_repository_surface(root: Path) -> None:
    missing = sorted(path for path in REQUIRED_DOCS if not (root / path).is_file())
    _require(not missing, f"required documentation missing: {missing}")
    present_forbidden = sorted(path for path in FORBIDDEN_PATHS if (root / path).exists())
    _require(not present_forbidden, f"forbidden repository paths present: {present_forbidden}")

    ignored_parts = {".git", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".venv", "__pycache__"}
    for path in sorted(item for item in root.rglob("*") if item.is_file()):
        if any(part in ignored_parts for part in path.parts):
            continue
        try:
            content = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        lowered = content.lower()
        for forbidden in FORBIDDEN_TEXT:
            _require(
                forbidden not in lowered, f"forbidden project text in {path.relative_to(root)}"
            )
        _require(
            FORBIDDEN_REGION not in content, f"blocked region present in {path.relative_to(root)}"
        )


def validate_foundation(root: Path | None = None) -> dict[str, Any]:
    """Validate the complete Part 1 repository contract and return a deterministic summary."""

    repository = root or Path(__file__).resolve().parents[2]
    schema_digests = _validate_schemas(repository)
    target = _validate_target(repository)
    completion = _validate_completion(repository, target)
    _validate_repository_surface(repository)

    payload: dict[str, Any] = {
        "project": PROJECT,
        "part": 1,
        "state": "PART1_FOUNDATION_COMPLETE",
        "aws_execution": False,
        "schema_digests": schema_digests,
        "target": {
            "repository": target["repository"],
            "default_branch": target["default_branch"],
            "account_id": target["account_id"],
            "region": target["region"],
            "oidc_role_name": target["oidc_role_name"],
            "managed_runtime": target["managed_runtime"],
        },
        "scorecard_targets": completion["scorecard"],
    }
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    payload["foundation_sha256"] = sha256(canonical).hexdigest()
    return payload


def main() -> None:
    print(json.dumps(validate_foundation(), indent=2, sort_keys=True))
